### ISSUE TITLE
MacOs compiling problems

### ISSUE THREAD

**Issue by maurorappa** [neural75/gqrx-scanner#1]
This is my setup:

Apples-MacBook-Pro:gqrx-scanner-master mauro$ uname -a
Darwin Apples-MacBook-Pro.local 16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64 x86_64
Apples-MacBook-Pro:gqrx-scanner-master mauro$ make -v
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for i386-apple-darwin11.3.0
Apples-MacBook-Pro:gqrx-scanner-master mauro$ gcc -v
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

This is my test:

gqrx-scanner-master mauro$ cmake .
-- The C compiler identification is AppleClang 8.1.0.8020042
-- The CXX compiler identification is AppleClang 8.1.0.8020042
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/mauro/Downloads/gqrx-scanner-master
Apples-MacBook-Pro:gqrx-scanner-master mauro$ make
Scanning dependencies of target gqrx-scanner
[ 33%] Building C object CMakeFiles/gqrx-scanner.dir/gqrx-scan.c.o
/Users/mauro/Downloads/gqrx-scanner-master/gqrx-scan.c:38:10: fatal error: 'stdio_ext.h' file not found
#include <stdio_ext.h>
         ^
1 error generated.
make[2]: *** [CMakeFiles/gqrx-scanner.dir/gqrx-scan.c.o] Error 1
make[1]: *** [CMakeFiles/gqrx-scanner.dir/all] Error 2
make: *** [all] Error 2

**Comment by neural75** [comment]
yes, there are two problems: linux/limits.h for PATH_MAX and stdio_ext.h for __fpurge().  You could include sys/syslimits.h for PATH_MAX and rename __fpurge in fpurge() instead, removing stdio_ext.h. Thank you for your detailed report. As soon as I have time I will fix it in master.

**Comment by jackf242** [comment]
+1 to fixing please. 10.13.6.

**Comment by neural75** [comment]
Merge a fix for this, thanks to rabarar. https://github.com/neural75/gqrx-scanner/pull/5#issue-254102025
