### ISSUE TITLE
ERROR opening gqrx bookmarks file: No such file or directory

### ISSUE THREAD

**Issue by TasosEL** [neural75/gqrx-scanner#10]
Is the path provided to OPEN function wrong?
This is the error I am getting when I run the examples

**Comment by neural75** [comment]
What's the errore?

**Comment by neural75** [comment]
The file Is ~/.config/gqrx/bookmarks.csv. Did you run from the same user running gqrx? Can you verify this file in your directory?

**Comment by TasosEL** [comment]
"Did you run from the same user running gqrx". I did this.
The file was not there.
I did a "touch bookmarks.csv" and it seems that it is working now.
What are the information included in the .csv file.

**Comment by neural75** [comment]
It's the Gqrx bookmark file. I don't understand your issue. Has Gqrx changed the default path where It stores the bookmark or you never saved any bookmark inside Gqrx?

**Comment by neural75** [comment]
bookmarks file missing possibly due to the fact gqrx had never run

**Comment by TasosEL** [comment]
I had run several times gqrx but the file was not there, thank you.

**Comment by febs** [comment]
I never saved any bookmarks so the file was not there. If not using the bookmarks mode I guess the check could be skipped?
