### ISSUE TITLE
Can this sweep the entire spectrum and write the active frequencies to a file?

### ISSUE THREAD

**Issue by NeuroForLunch** [neural75/gqrx-scanner#13]
Or is there software better suited for this purpose?

**Comment by neural75** [comment]
By command line parameters, It should.

Il ven 30 apr 2021, 01:03 NeuroForLunch ***@***.***> ha
scritto:

**Comment by NeuroForLunch** [comment]
What are the parameters for a sweep from 24Mhz to 1700Mhz ?

**Comment by neural75** [comment]
I'm on the go right now. Please, see the examples in the README.

Il ven 30 apr 2021, 19:57 NeuroForLunch ***@***.***> ha
scritto:

**Comment by NeuroForLunch** [comment]
I can see that it can do a sweep but I don't see how it can write to a file for sharing or reuse. 

This is in your readme:

TODOs
- [ ] set modulation in bookmark search
- [ ] automatic audio recording on signal detection
- [ ] parsable output in csv?

rtl-power does a sweep for a user set amount of time and writes to a csv which can then be used with heatmap.py to generate a heatmap, however, it only takes 1 sample per minute and there is no way to change that via command line parameters.

**Comment by neural75** [comment]
You can redirect the stdout to a file. CSV export, as you have already seen, is not implemented but you can extract data with some regex of needed.
The main purpose of the program is to scan and log the findings, not to dump the spectrum levels for heatmaps, but if I remember corrctly I output also the Signal level detected for each carrier above the threshold.
