### ISSUE TITLE
Squelch modifier

### ISSUE THREAD

**Issue by grappas** [neural75/gqrx-scanner#19]
**Is your feature request related to a problem? Please describe.**
Random signal spikes causes loop breaking or audible signals are choked by squelch.

**Describe the solution you'd like**
Squelch modifier - lets say --top_squelch <value in -dB> <-- that's a value that breaks the loop and let us hear an audio signal. After --top_squelch is broken gqrx-scanner immediately sets squelch to --bottom_squelch (have to be lower value than --top_squelch) and let us hear audible signal until it's below --bottom_squelch. After that squelch is set again as --top_squelch.

**Describe alternatives you've considered**
n/a

**Additional context**
Idea is from frequency-scanner plugin from SDR#. It was a workaround as "mute" (still measuring SNR and double squelch floor as the whole idea). It worked out pretty well.

**Comment by neural75** [comment]
@grappas : I had to change the short option to 'q' because of a conflict with 's' for frequency step of another PR.
