### ISSUE TITLE
ERROR connecting: Connection refused

### ISSUE THREAD

**Issue by Dr4il** [neural75/gqrx-scanner#2]
When i try to run gqrx-scanner typing: "./gqrx-scanner" i got a output:"ERROR connecting: Connection refused". What I'm doing wrong?

**Comment by trcyprkr** [comment]
i'm having the same problem.  I hope we can get some kind of solution

**Comment by neural75** [comment]
As stated in the notes you must start the remote protocol in Gqrx, follow this guide http://gqrx.dk/doc/remote-control

**Comment by trcyprkr** [comment]
i found the problem.  The button 'UDP' needs to be activated.
