### ISSUE TITLE
Using Squelch & Using Mode Saved in Bookmarks

### ISSUE THREAD

**Issue by BT-Justice** [neural75/gqrx-scanner#23]
How do you set the squelch exactly?  I assume it is the -q option, but how do you set a negative value?  I like to run the scanner at -60.0 dB.  I tried this but it gives me the "Error: -q: option requires an argument":

`-q -60.0`

Now if I use this, the scanner works, but on activity it resets the squelch to -110.0 dB:

`-q 60.0`

Also, how do you tell the scanner to use the mode saved to the bookmark?  I have a mix of AM and NFM frequencies I scan.  The mode doesn't switch on activity.

**Comment by grappas** [comment]
It's not setting exact squelch but squelch delta (that you can still set squelch inside gqrx). i.e.:
Inside gqrx you have set squelch to -50. SNR is around -38. You have "-q 10". If squelch ceiling is broken now squelch is set to -50 + 10 = -40. Signal goes under -40, squelch is set again to -50.

**Comment by grappas** [comment]
https://github.com/grappas/gqrx-scanner/tree/grappas/auto-squelch-delta introduces squelch auto mode.

@neural75 could you review it and eventually merge it?
