### ISSUE TITLE
Make error: initializer element is not constant

### ISSUE THREAD

**Issue by jonnycat5000** [neural75/gqrx-scanner#25]
Building on Ubuntu 18.04 I get the following error at the make stage: 

$ cmake .
-- Configuring done
-- Generating done
-- Build files have been written to: /home/jon/git/gqrx-scanner
jon@joncomp:~/git/gqrx-scanner$ make
[ 33%] Building C object CMakeFiles/gqrx-scanner.dir/gqrx-scan.c.o
/home/jon/git/gqrx-scanner/gqrx-scan.c:123:31: error: initializer element is not constant
 freq_t          opt_scan_bw = g_default_scan_bw;
                               ^~~~~~~~~~~~~~~~~
CMakeFiles/gqrx-scanner.dir/build.make:75: recipe for target 'CMakeFiles/gqrx-scanner.dir/gqrx-scan.c.o' failed
make[2]: *** [CMakeFiles/gqrx-scanner.dir/gqrx-scan.c.o] Error 1
CMakeFiles/Makefile2:83: recipe for target 'CMakeFiles/gqrx-scanner.dir/all' failed
make[1]: *** [CMakeFiles/gqrx-scanner.dir/all] Error 2
Makefile:135: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by neural75** [comment]
Ubuntu 18.04 is old, but I am pretty sure it was working back then. This is odd. No problem whatsoever on newer versions of Ubuntu. What version are you using for gcc? Is it the default compiler or are you using another C compiler instead ? (update-alternatives --query cc)
Anyway, try removing the const qualifier on the g_default_scan_bw definition, must be something regarding the assignment from the const storage and also because the file is .c and not cpp

**Comment by jonnycat5000** [comment]
Thanks neural, my version of gcc is the one from the standard repo and is reporting as 7.5.0:
$ gcc --version
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0

Not being a programmer I am unsure what I would need to do in the gqrx-scan.c file, but commenting out line 123  brought up other errors during make, all stating "error: ‘opt_scan_bw’ undeclared"  (I assume this would be expected).

**Comment by neural75** [comment]
I was unable to reproduce, not even switching to clang :( 
You should change this line 112:
const freq_t    g_default_scan_bw   = 10000;   // default scan frequency steps (10Khz)
to
freq_t    g_default_scan_bw   = 10000;   // default scan frequency steps (10Khz)
(removing the const)

**Comment by neural75** [comment]
Ok 7.5.0 cannot assign the value if the variable is global referring to another global (did not know), they should had fixed this in later releases.


instead of
freq_t          opt_scan_bw = g_default_scan_bw

Try this:
freq_t          opt_scan_bw = 10000;

this should work.

**Comment by jonnycat5000** [comment]
That did the trick, thanks neural, you da man!
