### ISSUE TITLE
uninstall target

### ISSUE THREAD

**Issue by LeonRonin** [neural75/gqrx-scanner#3]
hi
this is not an issue... I know.
but how do I uninstall this package from my machine? you haven't provided a uninstall target
I'm on ubuntu18 by the way
thank you

**Comment by neural75** [comment]
Just remove the binary gqrx-scanner in /usr/bin. There is no other
artifacts.
As soon as I have some time I will update the repo.
Bye,

Il gio 19 lug 2018, 07:38 LeonRonin <notifications@github.com> ha scritto:

**Comment by neural75** [comment]
Added in 1.0.1 release
