### ISSUE TITLE
Cmake errors

### ISSUE THREAD

**Issue by denhamgithub** [neural75/gqrx-scanner#7]
Linux Mint 19.1 based on Ubuntu 18.04. 

Cmake . Cmake run from directory '~/gqrx-addons/gqrx-scanner-master' I created that 'gqrx-addons' in /home/den. Cmake . failed with errors (should I have posted error log?--many lines but each says 'The output was: No such file or directory'.  

make then failed with output of 'make: *** No targets specified and no makefile found.  Stop.'  

For whatever it is worth, I had to install cmake with recommended 'sudo apt install cmake'.
Dennis E.

**Comment by lwvmobile** [comment]
Not quite sure what's going on without the log, but if your still interested or haven't figured it out, you should just use the following procedure:

`sudo apt install git cmake`
`git clone https://github.com/neural75/gqrx-scanner`
`cd gqrx-scanner`
`cmake .`
`make`

Then cd into the bin folder in the gqrx-scanner folder and run it with ./gqrx-scanner.
Optionally, you can install from terminal from the gqrx-scanner folder with
`sudo make install`

**Comment by neural75** [comment]
Close it because it's an old issue(not even sure). The LTS Ubuntu 20.04 is already out and the build is working.
